#ifndef STICKSC_ERROR
#define STICKSC_ERROR

#define STDIN_ERROR -1
#define THREAD_CREATE_ERROR -2
#define SERVER_CREATE_ERROR -3
#define CONNECTION_CREATE_ERROR -4
#define ENV_GET_ERROR -5
#define ARGS_ERROR -6
#define SERVER_SEND_ERROR -7
#define SERVER_RECV_ERROR -8
#define CONNECTION_SEND_ERROR -9
#define CONNECTION_RECV_ERROR -10
#define STDOUT_ERROR -11
#define NOT_REACHABLE -254
#define NOT_IMPLEMENTED -255

#endif /* ifdef ndef STICKSC_ERROR */
